apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirlingpdf-release
  namespace: stirlingpdf
spec:
  interval: 10m
  releaseName: stirlingpdf-release
  chart:
    spec:
      chart: stirlingpdf-repository
      version: '0.43.X'
      sourceRef:
        kind: HelmRepository
        name: stirlingpdf
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 1
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hosts:
        - name: stirling.bytedragon.tech
          path: /
    resources:
      limits:
        cpu: 500m  # Augmenté pour accélérer le démarrage
        memory: 512Mi  # Augmenté pour éviter les OOM
      requests:
        cpu: 100m
        memory: 256Mi
    probes:
      liveness:
        initialDelaySeconds: 60
      readiness:
        initialDelaySeconds: 60
