apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirlingpdf-release
  namespace: stirlingpdf
spec:
  interval: 10m
  releaseName: stirlingpdf-release
  chart:
    spec:
      chart: stirlingpdf-repository
      version: '0.43.X'
      sourceRef:
        kind: HelmRepository
        name: stirlingpdf
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 1
