apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/ingress-nginx
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---