#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: stirlingpdf
#  namespace: flux-system
#spec:
#  interval: 1m0s
#  path: ./apps/stirlingpdf
#  prune: true
#  wait: true
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#---